name: Create Github Release

on:
  push:
    tags:
      -"v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Tag Name and Message
        id: tag_info
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          TAG_MESSAGE=$(git for-each-ref refs/tags/$TAG_NAME --format='%(contents)')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "TAG_MESSAGE<<EOF" >> $GITHUB_OUTPUT
          echo "${TAG_MESSAGE}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.tag_info.outputs.TAG_NAME }}" --title "Release ${{ steps.tag_info.outputs.TAG_NAME }}" --notes "${{ steps.tag_info.outputs.TAG_MESSAGE }}"