name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      - name: Build wheel
        run: |
          python -m build --wheel --outdir dist
      - name: Install wheel
        run: |
          pip install dist/*.whl
      - name: Run test
        run: |
          python -m pip install pytest
          pytest tests/
